### PR TITLE
Add sousam9223-bond.toml

### PR DESCRIPTION
**Pull request by sousam9223**
## Discord handler
< .sousam >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
Looks like you have two PRs open, can you please move all your bonds into a single PR and close the other one?

**Comment by sousam9223** [comment]
> Looks like you have two PRs open, can you please move all your bonds into a single PR and close the other one?

Please tell me how to do this. I thought of delegating to different validators, these are two different transactions.

**Comment by iskay** [comment]
sure, just copy/paste all your bonds into a single file named `sousam9223-bond.toml` (don't forget filename should be only lowercase).

see this one for an example of how it should look: https://github.com/anoma/namada-mainnet-genesis/blob/main/transactions/brentstone-bond.toml

**Comment by sousam9223** [comment]
Thanks!

вт, 8 окт. 2024 г. в 00:43, Ian ***@***.***>:

**Pull request closed without merging**
