### PR TITLE
add CosmicValidator pre-genesis transactions

### PR DESCRIPTION
**Pull request by harish551**
## Discord handler
harish0x12

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — APPROVED** [review]

**Review by iskay — CHANGES_REQUESTED** [review]
the toml itself looks good, however the filename (CosmicValidator) needs to match your github name (harish551). can you either resubmit from CosmicValidator github account or change the filename? sorry, it's required by our CI checks for sybil reasons. Thanks!

**Comment by harish551** [comment]
> the toml itself looks good, however the filename (CosmicValidator) needs to match your github name (harish551). can you either resubmit from CosmicValidator github account or change the filename? sorry, it's required by our CI checks for sybil reasons. Thanks!

I thought it should match with github account which we are submitting PR

**Comment by iskay** [comment]
I think it needs to match the username of the user submitting the PR, @Fraccaman can correct me if I'm wrong here. Thanks for renaming, it's still failing but I think only due to a separate ci issue we need to resolve on our end

**Comment by iskay** [comment]
One last thing -- there was a glitch with the CI on our end which is why the checks are failing still. We've pushed a fix; can you please rebase to latest and see if the checks pass now?

**Comment by harish551** [comment]
> One last thing -- there was a glitch with the CI on our end which is why the checks are failing still. We've pushed a fix; can you please rebase to latest and see if the checks pass now?

Done, can you approve once ?

**Review by Fraccaman — APPROVED** [review]

**Review by iskay — APPROVED** [review]

**Pull request merged**
