### PR TITLE
Add Citadel.one pre-genesis transactions

### PR DESCRIPTION
**Pull request by Krewedk0**
## Discord handler
`krewedk0`

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — APPROVED** [review]

**Review by iskay — CHANGES_REQUESTED** [review]
looks good except there's a typo in the filename (extra 'v'). once fixed we can merge. Thanks!

**Comment by Krewedk0** [comment]
Oopsie, fixed the filename

**Comment by iskay** [comment]
One last thing -- there was a glitch with the CI on our end which is why the checks are failing still. We've pushed a fix; can you please rebase to latest and see if the checks pass now?

**Comment by Krewedk0** [comment]
Done

**Review by iskay — APPROVED** [review]

**Pull request merged**
