### PR TITLE
add mnm-is-aleks pre-genesis transactions

### PR DESCRIPTION
**Pull request by mnm-is-aleks**
## Discord handler
alezz7997

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
Hey! Thanks for submitting your pre-genesis transaction :) in phase 1, we are only allowing pre-genesis transactions to init a validator. Could you please remove the self-bond tx? thanks

**Comment by mnm-is-aleks** [comment]
Hi! Sure, I'll remove the self-bond transaction

**Comment by mnm-is-aleks** [comment]
Done! I've removed bond.toml

**Comment by mnm-is-aleks** [comment]
> Hey! Thanks for submitting your pre-genesis transaction :) in phase 1, we are only allowing pre-genesis transactions to init a validator. Could you please remove the self-bond tx? thanks

Done! I've removed bond.toml

**Comment by Fraccaman** [comment]
@mnm-is-aleks  we had to update some of the CI scripts, do u mind rebasing on main so CI passes?

**Comment by mnm-is-aleks** [comment]
> @mnm-is-aleks we had to update some of the CI scripts, do u mind rebasing on main so CI passes?

Done

**Review by Fraccaman — APPROVED** [review]

**Pull request merged**
