### PR TITLE
Create decanus-validator.toml

### PR DESCRIPTION
**Pull request by decanus**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
pls rename the file using your github alias

**Comment by decanus** [comment]
@Fraccaman the validator isn't a personal one, but one for my organization.

**Comment by Fraccaman** [comment]
doesn't matter, this is needed for internal management

**Comment by decanus** [comment]
done

**Review by Fraccaman — DISMISSED** [review]

**Comment by Fraccaman** [comment]
the signatures are invalid

**Comment by decanus** [comment]
@Fraccaman updated

**Review by iskay — DISMISSED** [review]

**Review by iskay — APPROVED** [review]

**Pull request merged**
