### PR TITLE
Add creeea-bond.toml

### PR DESCRIPTION
**Pull request by creeea**
## Discord handler
creeea

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
Thanks for you PR! Can you submit a single file with all the bonds tx together pls?

**Comment by creeea** [comment]
> Thanks for you PR! Can you submit a single file with all the bonds tx together pls?

Does this work? They have different source addresses.

**Comment by iskay** [comment]
@creeea yes, as long as all the keys corresponding to the different sources are in your wallet, you can sign them all in one command. just copy/paste all three (unsigned) bonds into one toml file and sign that toml with `namadac utils sign-genesis-txs`. it will find the right keys for each bond automatically

**Comment by creeea** [comment]
> @creeea yes, as long as all the keys corresponding to the different sources are in your wallet, you can sign them all in one command. just copy/paste all three (unsigned) bonds into one toml file and sign that toml with `namadac utils sign-genesis-txs`. it will find the right keys for each bond automatically

I signed each bond individually and merged signed bonds into a single file. If this won't pass (it should) I'll go your route.

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
all good! thanks

**Pull request merged**
