### PR TITLE
Create rossoman-bond.toml

### PR DESCRIPTION
**Pull request by rossoman**
## Discord handler
rossoman

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — APPROVED** [review]

**Comment by iskay** [comment]
@rossoman got `Invalid transfer tx. Source tnam1qzapwdp5ldskua87lqd0nd2kcc7pjeljvqxt770v has no balance of token "nam".`
did you use the right key?

**Comment by rossoman** [comment]
> @rossoman got `Invalid transfer tx. Source tnam1qzapwdp5ldskua87lqd0nd2kcc7pjeljvqxt770v has no balance of token "nam".` did you use the right key?

Hi! Yes I used the correct key, I have a non-standard situation, I have a balance on the validator address  (established account address):

tnam1qxgukz303wrw5xkcfy3agpc4lh2s7e7l0ucu6n0w

**Comment by Fraccaman** [comment]
`0191cb0a2f8b86ea1ad84923d40715fdd50f67df7f` is not part of `balances.toml` not sure whats going on here

**Comment by rossoman** [comment]
@Fraccaman @iskay updated the file, used another public key, where the public key is definitely in the balances file, just the previous one (in the balance file is the validator wallet, that's probably why it doesn't work, apparently only after genesis)

**Review by iskay — APPROVED** [review]

**Pull request merged**
