### PR TITLE
AutoStake-com-bond.toml

### PR DESCRIPTION
**Pull request by AutoStake-com**
## Discord handler
autostake

## Checklist before opening a pull request
- [X] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [X] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
contents look good but pls rename file to `AutoStake-com-bond.toml`

**Comment by AutoStake-com** [comment]
> contents look good but pls rename file to `AutoStake-com-bond.toml`

Will do, apologies

**Comment by Fraccaman** [comment]
filename is still wrong

**Comment by AutoStake-com** [comment]
> filename is still wrong

Yes, your right, apologies again

Fixed now

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
should be all good now! welcome abord!

**Pull request merged**
