### PR TITLE
Add sigv-bond.toml

### PR DESCRIPTION
**Pull request by sigv**
## Discord handler
signalv

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
@sigv thanks for the submission! can you try to rebase on `main` pls?

**Comment by sigv** [comment]
It's failing the check, as `tpknam` balance is considered zero. Moving this to the Discord for discussion and visibility.

**Comment by sigv** [comment]
fwiw, I have also allowed the team members to push changes, so you should also be able to rebase.

**Comment by Fraccaman** [comment]
can't you bond from ur implicit address?

**Comment by Fraccaman** [comment]
sorry this was completely my fault, the bug was in this repository CI. Please, rebase another time, should be the last one!

**Review by iskay — APPROVED** [review]

**Pull request merged**
