### PR TITLE
Add Olexandr-bond.toml

### PR DESCRIPTION
**Pull request by Olexandr88**
## Discord handler
< insert here you discord handler (oleksandr5465) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
`Invalid bond tx signature: The section signature is invalid: found invalid signature.`

**Comment by Olexandr88** [comment]
Hi. Please take a look at my application

**Comment by Olexandr88** [comment]
Can I delete this request and create a new one?

**Comment by Fraccaman** [comment]
yes

**Pull request closed without merging**
