### PR TITLE
Add polblancoo-bond.toml

### PR DESCRIPTION
**Pull request by polblancoo**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
@polblancoo please rename the file to `polblancoo-bond.toml`

**Comment by polblancoo** [comment]
Done -Tk!

**Comment by iskay** [comment]
Looks like you edited the PR title but not the filename itself

**Comment by iskay** [comment]
Thanks for submitting. This PR was done incorrectly. Please see https://hackmd.io/@gaving/SJCFAP8aR or ask for support in #pre-genesis chatter: https://discord.com/invite/namada

**Pull request closed without merging**
