### PR TITLE
Add StakinOfficial-bond.toml

### PR DESCRIPTION
**Pull request by EdouardLvdl**
## Discord handler
edouardlvdl

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by Fraccaman — DISMISSED** [review]

**Comment by EdouardLvdl** [comment]
Ok, thank you for the feedback @Fraccaman 

The instructions did specify to name the file "github_username-bond.toml". I would be happy to name it with the fork github repo instead.

On the phase 1 I also used github_username instead of the forked repo admin (StakinOfficial)

Do you confirm I should now rename the file to `StakinOfficial-bond.toml` ?

**Comment by Fraccaman** [comment]
yes please!

**Comment by EdouardLvdl** [comment]
I've renamed the file as well as the Github PR @Fraccaman. Let me know! Thank you

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
`A duplicate address "tnam1qy9jra0mueg9637r0wlxehecrj0ale9ldgrytymm" found in a `established_account` tx.\nA duplicate validator "tnam1qy9jra0mueg9637r0wlxehecrj0ale9ldgrytymm" found in a `validator_account` tx.`

**Comment by EdouardLvdl** [comment]
Thank you will close this PR and double check things

**Pull request closed without merging**
