### PR TITLE
Add cosmowiz pre-genesis transactions.

### PR DESCRIPTION
**Pull request by cosmowiz**
## Discord handler
< cosmowizard >

### CODE REVIEW

**Comment by iskay** [comment]
ty for re-opening; there's still a ci issue but we'll look into it from our end. no worries, still plenty of time to get it sorted before stage 2

**Comment by cosmowiz** [comment]
> ty for re-opening; there's still a ci issue but we'll look into it from our end. no worries, still plenty of time to get it sorted before stage 2

update once ready here please!

**Comment by cosmowiz** [comment]
> ty for re-opening; there's still a ci issue but we'll look into it from our end. no worries, still plenty of time to get it sorted before stage 2

what if i just resubmit it with new address? was issue solved with checker?

**Comment by iskay** [comment]
@cosmowiz sorry for the delay! i've tested your file locally and it's valid. i see now there's a typo in your filename, there's an extra `.` at the end. (don't know how i missed that the first time). pls rename and see if that finally fixes the ci -- if not i can merge manually for you

**Comment by cosmowiz** [comment]
> @cosmowiz sorry for the delay! i've tested your file locally and it's valid. i see now there's a typo in your filename, there's an extra `.` at the end. (don't know how i missed that the first time). pls rename and see if that finally fixes the ci -- if not i can merge manually for you

Please merge manualy! Looks like i just copied it wrongly from docs

**Comment by cosmowiz** [comment]
resubmit

**Pull request closed without merging**
