### PR TITLE
update automatic bonds to 18-10-2024

### PR DESCRIPTION
**Pull request by dimiandre**
update automatic bonds to 18-10-2024

800~ bonds!

### CODE REVIEW

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
Some of the tx have a duplicated signature, can you check?

**Comment by dimiandre** [comment]
> Some of the tx have a duplicated signature, can you check?

done!

**Review by Fraccaman — DISMISSED** [review]

**Comment by Fraccaman** [comment]
```Invalid bond tx. Source tnam1qzq9mglfz4p2pah9wwdux8wetqyxjdgvpvxdw27t doesn't have enough balance of token "nam" to transfer 20000. Got 3333.33.
Invalid bond tx. Source tnam1qqfhhcl9xq4j3gdz5l43rqf4yzxjlhuntv6sxgyg doesn't have enough balance of token "nam" to transfer 6485.58. Got 6385.584122.```

**Comment by dimiandre** [comment]
> Invalid bond tx. Source tnam1qzq9mglfz4p2pah9wwdux8wetqyxjdgvpvxdw27t doesn't have enough balance of token "nam" to transfer 20000. Got 3333.33.
> 
> Invalid bond tx. Source tnam1qqfhhcl9xq4j3gdz5l43rqf4yzxjlhuntv6sxgyg doesn't have enough balance of token "nam" to transfer 6485.58. Got 6385.584122.

sorry for that! 

fixed now

**Review by Fraccaman — APPROVED** [review]

**Pull request merged**
