### PR TITLE
add rickzahng2024-bond.toml

### PR DESCRIPTION
**Pull request by rickzahng2024**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
can you pls rename the file to `rickzahng2024-bond.toml`

**Comment by vitek1273** [comment]
Vitek1273

**Comment by rickzahng2024** [comment]
> 您能将该文件重命名为吗`rickzahng2024-bond.toml`？

OK.

**Review by iskay — APPROVED** [review]

**Comment by iskay** [comment]
Thanks for your interest! There still appear to be some issues with the PR. Since the deadline for pre-genesis was Oct 18 @ 1700 UTC, I'll close it. You can still delegate as soon as mainnet genesis launches using any staking interface.

**Pull request closed without merging**
