### PR TITLE
pre-genesis

### PR DESCRIPTION
**Pull request by Michel-Leidson**
StakePool
https://stakepool.dev.br/

### CODE REVIEW

**Review by iskay — CHANGES_REQUESTED** [review]
toml itself looks good! but
1. looks like you accidentally included the same file under two different names
2. I believe the CI checks require the name in the file (stakepool) to match your github name (Michel-Leidson). so either change the filename or submit from your stakepool github

once these are taken care of we can merge

**Comment by Michel-Leidson** [comment]
Done!

**Comment by iskay** [comment]
Ty! it's still failing but I believe due to a CI issue on our end... once we resolve that I expect it to pass

**Comment by Michel-Leidson** [comment]
Thanks a lot!

**Comment by iskay** [comment]
We've pushed a fix for the CI bug, can you try rebasing to latest to see if the checks pass?

**Comment by Michel-Leidson** [comment]
Yes, of course.

**Review by Fraccaman — APPROVED** [review]

**Comment by Michel-Leidson** [comment]
I closed the pr: And reopen a new one #54 with new changes.

**Pull request closed without merging**
