### PR TITLE
Add maximmaslii-bond.toml

### PR DESCRIPTION
**Pull request by MaximMaslii**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
Can you please rename the filename using only lowercase letters, for our CI checks?

**Comment by MaximMaslii** [comment]
> Can you please rename the filename using only lowercase letters, for our CI checks?

Hi. Ok done

**Comment by iskay** [comment]
ty but you've only changed the PR title, please change the actual filename as well

**Comment by MaximMaslii** [comment]
> ty but you've only changed the PR title, please change the actual filename as well

Hi. Now is ok?

**Comment by iskay** [comment]
sorry but no, it's still uppercase

**Pull request closed without merging**
