### PR TITLE
Add reversesigh pre-genesis transactions

### PR DESCRIPTION
**Pull request by reversesigh**
## Discord handler
reversesigh

## Checklist before opening a pull request
- [X] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [X] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — CHANGES_REQUESTED** [review]
sorry for any inconvenience, but our CI requires that you only submit the validator toml right now, and submit the bond toml later during stage 2. can you remove the bond toml from this PR? then we can merge, everything else looks good - Thanks!

**Comment by reversesigh** [comment]
> sorry for any inconvenience, but our CI requires that you only submit the validator toml right now, and submit the bond toml later during stage 2. can you remove the bond toml from this PR? then we can merge, everything else looks good - Thanks!

Done!

**Comment by iskay** [comment]
Thanks! looks good but there was a glitch with the CI on our end which is why the checks are failing still. We've pushed a fix; can you please rebase to latest and see if the checks pass now?

**Comment by reversesigh** [comment]
> Thanks! looks good but there was a glitch with the CI on our end which is why the checks are failing still. We've pushed a fix; can you please rebase to latest and see if the checks pass now?

Sure thing! Done.

**Review by Fraccaman — APPROVED** [review]

**Review by iskay — APPROVED** [review]

**Pull request merged**
