### PR TITLE
Create Validator-POSTHUMAN-bond.toml

### PR DESCRIPTION
**Pull request by web3validator**
## Discord handler
posthuman_validator

## Checklist before opening a pull request
- [+] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [+] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
Can you pls rename the file to `web3validator-bond.toml`

**Comment by Antropocosmist** [comment]
https://github.com/web3validator - part of  POSTHUMAN core-team

He create pull request from organization https://github.com/Validator-POSTHUMAN

The list of core-team mebers can be found here: https://github.com/Validator-POSTHUMAN/core-team

**Comment by Fraccaman** [comment]
sure, but for internal reasons, we need the file to be named `web3validator-bond.toml`

**Comment by web3validator** [comment]
Done!

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
`Invalid bond tx. Source tnam1qzx2zpxw3vw5gg9c3qrj7ngdqu0hgf2mzs0tl0mc doesn't have enough balance of token "nam" to transfer 4000. Got 1110.110863.`

**Comment by web3validator** [comment]
Also just in case the previous validator toml file https://github.com/anoma/namada-mainnet-genesis/blob/main/transactions/POSTHUMAN-validator.toml  was passed as Validator-POSTHUMAN.toml file and not the github name of the person submitting the PR

**Comment by Fraccaman** [comment]
> Also just in case the previous validator toml file [`main`/transactions/POSTHUMAN-validator.toml](https://github.com/anoma/namada-mainnet-genesis/blob/main/transactions/POSTHUMAN-validator.toml) was passed as Validator-POSTHUMAN.toml file and not the github name of the person submitting the PR

unlucky but no problem

**Comment by Fraccaman** [comment]
> It seems like @Antropocosmist already delegated 3000 NAM through this PR #434. What’s the best option we can do? Will it be fine to recreate the genesis bond to 1k?

you can either replace the old bond, or make a new bond of 1k (if you want to delegate a total of 4k)

**Comment by Antropocosmist** [comment]
Please, check this: https://github.com/anoma/namada-mainnet-genesis/pull/675

After we will create new PR posthuman-validator.toml with 4000 NAM

**Comment by iskay** [comment]
@Antropocosmist #675 has been merged

**Comment by Antropocosmist** [comment]
I created new PR: https://github.com/anoma/namada-mainnet-genesis/pull/681

This is 4000 NAM for POSTHUMAN validator

**Review by iskay — APPROVED** [review]

**Pull request merged**
