### PR TITLE
Add Olexandr88-bond.toml

### PR DESCRIPTION
**Pull request by Olexandr88**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
pls rename the file to `olexandr88-bond.toml`

**Comment by Olexandr88** [comment]
Ok

**Comment by Fraccaman** [comment]
the filename not the PR title

**Comment by Olexandr88** [comment]
> the filename not the PR title

Sorry. Changed

**Comment by Fraccaman** [comment]
there is something wrong with the file u submitted, probably the signature or you copied it wrongly, can u try to resubmit?

**Pull request closed without merging**
