### PR TITLE
Add SerhiiManzhos pre-genesis transactions

### PR DESCRIPTION
**Pull request by SerhiiManzhos**
## Discord handler
serhii_piertwo

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
can you rename both files to lowercase?

**Comment by SerhiiManzhos** [comment]
> can you rename both files to lowercase?

sure. 5 minutes ))

**Comment by SerhiiManzhos** [comment]
> can you rename both files to lowercase?

check please

**Review by Fraccaman — APPROVED** [review]

**Comment by SerhiiManzhos** [comment]
@Fraccaman Thanks

**Comment by Fraccaman** [comment]
`Invalid transfer tx. Source tnam1qrg84njj7uedzs8xe584lularqvare2xmu8yje63 has no balance of token "nam".`

**Comment by SerhiiManzhos** [comment]
> `Invalid transfer tx. Source tnam1qrg84njj7uedzs8xe584lularqvare2xmu8yje63 has no balance of token "nam".`
```
namadaw find --alias PierTwo
Found transparent keys:
  Alias "piertwo" (encrypted):
    Public key hash: D07ACE52F732D140E6CD0F5FF3FD1819D1E546DF
    Public key: tpknam1qzepp9xeqpwlej9cq0t3r5e2rc8lgtkh7s0q0ac9xvhc6ujxxq05vn6dmv7
Found transparent address:
  "piertwo": Implicit: tnam1qrg84njj7uedzs8xe584lularqvare2xmu8yje63
```
namadac balance --owner PierTwo --token nam
nam: 2000

[7F36AEBD7E643FE6F056F55D11F85C01511A6122959E9A4F0B2BE7F6C1366ADD](https://shielded.live/txs/7F36AEBD7E643FE6F056F55D11F85C01511A6122959E9A4F0B2BE7F6C1366ADD)
[8F07D56802EBA0D92A818BEB86F1A83D8BDF4E52330DC9362C63A22AD86DED15](https://shielded.live/txs/8F07D56802EBA0D92A818BEB86F1A83D8BDF4E52330DC9362C63A22AD86DED15)
[D5E08F5937336A014241CF0C929035DD3BF412EE1F27A06E4AB83BBA4ABFD8DB](https://shielded.live/txs/D5E08F5937336A014241CF0C929035DD3BF412EE1F27A06E4AB83BBA4ABFD8DB)

Could you please check if I made any mistakes when creating the files?

**Comment by SerhiiManzhos** [comment]
> `Invalid transfer tx. Source tnam1qrg84njj7uedzs8xe584lularqvare2xmu8yje63 has no balance of token "nam".`

```
namadac balance --owner PierTwo --token nam --node https://rpc.knowable.run
nam: 2500
```

**Comment by iskay** [comment]
hi @SerhiiManzhos , to make a pre-genesis bond your address needs to have a balance in the `balances.toml` file (https://raw.githubusercontent.com/anoma/namada-genesis/refs/heads/main/balances.toml). To be included in that file, you would have needed to have received an allocation beforehand, eg. from an airdrop or from participating in the Shielded Expedition.

**Comment by SerhiiManzhos** [comment]
@iskay 
So, if I didn't participate in the Shielded Expedition and didn't receive an airdrop, does that mean I can't fully participate in the HouseFire testnet? Please understand me correctly. My task is to complete all the necessary actions to participate in the testnet and then move on to the mainnet. As I understand it, I need to launch a validator and follow the steps from the instructions https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view

Is there currently any way to add myself to the balances.toml? I need a method or instructions that will allow me to complete these steps. Could you please help

**Comment by iskay** [comment]
1. yes, you can definitely participate in the housefire testnet. there are bounties if you're able to halt the chain or find some other bug -- that is one way you could earn mainnet NAM. you can also run a node/validator for fun or for practice. but having a balance on housefire doesn't translate into mainnet NAM, it's just a testing environment.

2. the instructions in that link are only needed if you want to run a validator on mainnet at genesis time. if you just want to run on housefire, or if you want to run a validator on mainnet at some point after launch, you don't need to worry about those.

3. unfortunately, we can't add you to balances.toml, as that would be the same as giving you mainnet NAM which is not ours to give away

**Comment by SerhiiManzhos** [comment]
> 1. yes, you can definitely participate in the housefire testnet. there are bounties if you're able to halt the chain or find some other bug -- that is one way you could earn mainnet NAM. you can also run a node/validator for fun or for practice. but having a balance on housefire doesn't translate into mainnet NAM, it's just a testing environment.
> 2. the instructions in that link are only needed if you want to run a validator on mainnet at genesis time. if you just want to run on housefire, or if you want to run a validator on mainnet at some point after launch, you don't need to worry about those.
> 3. unfortunately, we can't add you to balances.toml, as that would be the same as giving you mainnet NAM which is not ours to give away

Can I buy NAM somewhere to participate? If not, then I understand that if I didn't participate in the Shielded Expedition, I currently can't launch a validator for the mainnet?

If I participate in the Housefire testnet, can I launch a validator in the mainnet afterwards?

Based on your responses, I understand that there is currently no opportunity to join the mainnet

**Comment by iskay** [comment]
in your situation, you can create a pre-genesis validator but you if you don't have any tokens to bond, you would need to have someone else who does already have some bond them to your validator.

keep in mind, this process is only for the genesis block. you can still create a validator at any time in the future after the network launches!

**Comment by gavinly** [comment]
@SerhiiManzhos you can create a validator without having anything bonded. when your validator has a delegation of 1000 or more NAM, it will be able to enter the active set. i recommend updating your PR to remove the bond so that your validator can be created

**Comment by iskay** [comment]
I'm going to close this PR -- if you have any more questions please feel free to ask in the Namada Discord. Thanks for your interest!

**Pull request closed without merging**
