### PR TITLE
Add PolkachuIntern pre-genesis transactions

### PR DESCRIPTION
**Pull request by PolkachuIntern**
## Discord handler
< polkachu >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
Hi! Bonds are allowed only during the second phase! Could you please remove the -bond file?

**Comment by PolkachuIntern** [comment]
sure thing. Just a minute. 

Oh, I see you just updated the instruction on hackdm. I was about to point my fingers.

**Comment by PolkachuIntern** [comment]
deleted the bond tx

**Review by Fraccaman — APPROVED** [review]

**Comment by PolkachuIntern** [comment]
thanks for merging. a quick question: when will I get the discord role?

**Pull request merged**
