### PR TITLE
Add GAGRIVA-bond.toml

### PR DESCRIPTION
**Pull request by GAGRIVA**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
can you please rename the file to lowercase?

**Comment by GAGRIVA** [comment]
Help me. I dont know to how do to that:(

вт, 8 окт. 2024 г. в 12:34, Fraccaroli Gianmarco ***@***.***>:

**Comment by Fraccaman** [comment]
the file you submitted its empty and should be all lowercase. You can try to fix it by re-submitting a new PR!

**Comment by iskay** [comment]
Thanks for your interest! Since the deadline for pre-genesis was Oct 18 @ 1700 UTC, I'll close this PR. You can still delegate as soon as mainnet genesis launches using any staking interface.

**Pull request closed without merging**
