### PR TITLE
Add rchas pre-genesis transactions

### PR DESCRIPTION
**Pull request by rchas**
## Discord handler
ches0494

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — CHANGES_REQUESTED** [review]
Hi rchas, looks like there's a problem with the signature at the end (missing " and wrong number of characters). can you please try re-doing the signature?

**Comment by rchas** [comment]
> Hi rchas, looks like there's a problem with the signature at the end (missing " and wrong number of characters). can you please try re-doing the signature?

i change, check please

**Comment by iskay** [comment]
ty but still not passing... you signature is 123 characters long but it should only be 117. so something's gone wrong somewhere -- probably will need to repeat the signing process from the beginning

**Comment by rchas** [comment]
> ty but still not passing... you signature is 123 characters long but it should only be 117. so something's gone wrong somewhere -- probably will need to repeat the signing process from the beginning

I checked and updated the file again, everything should be ok, if it doesn’t work this time, I’ll make a new one

**Review by iskay — APPROVED** [review]

**Comment by iskay** [comment]
yep, looks good. ty!

**Pull request merged**
