### PR TITLE
Add SHA25Six pre-genesis transactions

### PR DESCRIPTION
**Pull request by SHA25Six**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [X] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [X] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by SHA25Six** [comment]
Not sure why the .toml file is marked invalid?

**Comment by Fraccaman** [comment]
can try to rename the toml file to lowercase?

**Comment by SHA25Six** [comment]
> can try to rename the toml file to lowercase? i.e: `sha25six-bond.toml`

That did the job, thank you!

**Review by Fraccaman — APPROVED** [review]

**Comment by Fraccaman** [comment]
`Invalid bond tx. Source tnam1qrw2ysluy2sxvjh059hnpz00gxyza4zf5sg9z7f3 doesn't have enough balance of token "nam" to transfer 105. Got 1.880076.`

**Comment by SHA25Six** [comment]
> `Invalid bond tx. Source tnam1qrw2ysluy2sxvjh059hnpz00gxyza4zf5sg9z7f3 doesn't have enough balance of token "nam" to transfer 105. Got 1.880076.`

I see now that kintsugi's auto-submission has already been merged. It was explained a manual PR would overwrite that but seems not to be the case. Thanks for your help and apologies for the confusion - will close this PR then.

**Pull request closed without merging**
