### PR TITLE
Add Olexandr88-bond.toml

### PR DESCRIPTION
**Pull request by Olexandr88**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Olexandr88** [comment]
Please check

**Comment by Olexandr88** [comment]
Sorry, but if there is a problem again, I can already guess where I made a mistake. When I first committed, I decided to change the number of coins in the description because of the extension, I indicated 100, and on Github I decided to change it to 110

**Comment by iskay** [comment]
Ty for resubmitting, can you please rename the file using lowercase only?

**Comment by Olexandr88** [comment]
> Ти за повторне надсилання, чи можеш ти перейменувати файл, використовуючи лише малі літери?

Done

**Review by iskay — APPROVED** [review]

**Pull request merged**
