### PR TITLE
Update miles-six-bond.toml

### PR DESCRIPTION
**Pull request by miles-six**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by dimiandre** [comment]
signature is invalid

**Comment by gavinly** [comment]
@miles-six you're using the same signature you used for bonding 1000 NAM, but you've increased this, so it will require a new signature

**Comment by iskay** [comment]
@miles-six just bumping this in case you still want to get it merged before the deadline

**Comment by iskay** [comment]
Thanks for your interest! But it looks like this PR can't be merged with the invalid signature. Since the deadline for pre-genesis was Oct 18 @ 1700 UTC, I'll close this PR. You can still delegate as soon as mainnet genesis launches using any staking interface.

**Pull request closed without merging**
