### PR TITLE
Add kenneth-xyz pre-genesis transactions

### PR DESCRIPTION
**Pull request by kenneth-xyz**
## Discord handler
blocknthxyz

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
This pr looks good but it's not triggering the CI and I'm unsure why... could you pls do us a favour and close then re-open?

**Comment by kenneth-xyz** [comment]
It doesn't seem to be working

**Comment by iskay** [comment]
ty for re-opening; there's still a ci issue but we'll look into it from our end. no worries, still plenty of time to get it sorted before stage 2 (also affecting one other pr)

**Comment by kenneth-xyz** [comment]
@iskay

**Comment by iskay** [comment]
@kenneth-xyz sorry for the delay! i've tested your file locally and it's valid. i see now that your filename is missing the `.toml` extension. (don't know how i missed that the first time). pls rename and see if that finally fixes the ci -- if not i can merge manually for you

**Pull request closed without merging**
