### PR TITLE
Add miles-bond.toml

### PR DESCRIPTION
**Pull request by miles-six**
## Discord handler
< sixmiles >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by miles-six** [comment]
> ty! minor change, could you please rename the files `miles-six-validator.toml` and `miles-six-bond.toml` respectively?

pls check it sir

**Review by iskay — APPROVED** [review]

**Comment by miles-six** [comment]
I don't know why, but changing the file name from 'miles-validator' to 'miles-six-validator' causes the test to fail. Could you please help me? @iskay @Fraccaman

**Comment by Fraccaman** [comment]
you already submitted a validator init tx i think

**Comment by miles-six** [comment]
> you already submitted a validator init tx i think

so sir, what should I do

**Pull request closed without merging**
