### PR TITLE
add kostzen-bond.toml

### PR DESCRIPTION
**Pull request by KostZen**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
hey, can you lowercase the filename?

**Comment by KostZen** [comment]
done

**Comment by Fraccaman** [comment]
i dont see it lowercase

**Comment by KostZen** [comment]
done))

**Review by Fraccaman — APPROVED** [review]

**Pull request merged**
