### PR TITLE
Add tausifxd-bond.toml

### PR DESCRIPTION
**Pull request by tausifXD**
## Discord handler
@fancraze

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
Can you rename the filename to use only lowercase please?

**Comment by tausifXD** [comment]
> Can you rename the filename to use only lowercase please?

done :)

**Comment by iskay** [comment]
Ty! but I think you only changed the PR title and not the actual filename

**Comment by tausifXD** [comment]
> Ty! but I think you only changed the PR title and not the actual filename

ohh so sorry, done that now, please let me know if the bonding is successful

**Review by iskay — APPROVED** [review]

**Pull request merged**
