### PR TITLE
rayray2k-bond.toml

### PR DESCRIPTION
**Pull request by rayray2k**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
Can you please rename the file `rayray2k-bond.toml`

**Comment by rayray2k** [comment]
Renamed it to:  rayray2k-bond.toml

**Comment by rayray2k** [comment]
Done. Pls advise. Thx

**Comment by iskay** [comment]
ty but you've only renamed the PR title, not the file itself

**Comment by rayray2k** [comment]
Ok, renamed the file. TY

**Review by Fraccaman — APPROVED** [review]

**Pull request merged**
