### PR TITLE
Add lyeoeon1 pre-genesis transactions

### PR DESCRIPTION
**Pull request by lyeoeon1**
## Discord handler
lyeoeon

## Checklist before opening a pull request
- [ ] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [ ] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Review by iskay — CHANGES_REQUESTED** [review]
ty for updating! one last request, can you pls delete the first toml you had created (as it was already merged into main)

**Comment by lyeoeon1** [comment]
> ty for updating! one last request, can you pls delete the first toml you had created (as it was already merged into main)

I have removed the old TOML file as requested. Please let me know if there's anything else needed.

**Review by iskay — APPROVED** [review]

**Comment by lyeoeon1** [comment]
Thank you for approving the changes. I noticed the pull request was removed from the merge queue due to failed status checks, but I can't see any specific errors in the automated checks.

**Review by iskay — CHANGES_REQUESTED** [review]
almost there... ci issue is fixed but the signatures are not passing. can you pls try re-doing the signature? apologies for the back and forth

**Comment by lyeoeon1** [comment]
> almost there... ci issue is fixed but the signatures are not passing. can you pls try re-doing the signature? apologies for the back and forth

@iskay I have re-signed the original transactions.toml file and renamed it to lyeoeon1-validator.toml as requested. The file now includes the updated signature. Please review and let me know if any further changes are needed. Thank you for your patience and guidance throughout this process.

**Review by iskay — APPROVED** [review]

**Comment by iskay** [comment]
@lyeoeon1 looks good and merged. thanks for the prompt response, see you on mainnet!

**Pull request merged**
