### PR TITLE
Add Nodes.Guru pre-genesis transactions

### PR DESCRIPTION
**Pull request by kinrokinro**
## Discord handler
`0xan_nodes_guru`

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
Hi! thanks for you PR, but the file submitted has a wrong name: it should be named: `<github_alias>-validator.toml` i.e `kinrokinro-validator.toml`

**Comment by kinrokinro** [comment]
> Hi! thanks for you PR, but the file submitted has the wrong name: it should be named: `<github_alias>-validator.toml` i.e `kinrokinro-validator.toml`

Fixed

**Review by Fraccaman — DISMISSED** [review]

**Comment by Fraccaman** [comment]
uhmmmm seems like the signatures are not valid, checks are failing

**Comment by kinrokinro** [comment]
> uhmmmm seems like the signatures are not valid, checks are failing

Let me fix this 🙏

**Comment by kinrokinro** [comment]
> uhmmmm seems like the signatures are not valid, [checks are failing](https://0bin.net/paste/WJyHu8eK#3nv7Tm62VVhbaRSbmOL3nO3RC4y8qWgegL8HEFDK9P1)

Should be fixed now

**Comment by Fraccaman** [comment]
@kinrokinro we had to update some of the CI scripts, do u mind rebasing on main so CI passes?

**Comment by kinrokinro** [comment]
> @kinrokinro we had to update some of the CI scripts, do u mind rebasing on main so CI passes?

Done, waiting

**Review by iskay — APPROVED** [review]

**Pull request merged**
