### PR TITLE
add Encapsulate (fka KingSuper) bond stage 2

### PR DESCRIPTION
**Pull request by aditya-manit**
## Discord handler
kingsuper

## Checklist before opening a pull request
- [X] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [X] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
`tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw` is not part of balances.toml, just for info

**Comment by aditya-manit** [comment]
> `tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw` is not part of balances.toml, just for info

It is the public key for tnam1qpz93yrdr7d8g773lxj4h53c27kudz3ddvl9yd46 which is present in balances.toml

Let me know if that wont work ?

**Comment by Fraccaman** [comment]
I dont think `tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw` is part of balances.toml?

**Comment by aditya-manit** [comment]
> tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw

Yes its not, but balances.toml have transparent addresses (tnam1) not Public keys (tpknam1)

The transparent address for tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw is tnam1qpz93yrdr7d8g773lxj4h53c27kudz3ddvl9yd46 and it is present

**Comment by aditya-manit** [comment]
Should I be using tnam1qpz93yrdr7d8g773lxj4h53c27kudz3ddvl9yd46 instead of tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw in source field ?

```
[[bond]]
source = "tpknam1qzluhwmzp9aek7hpvj8a2q8afacw4gcjs5g457cjq4l5sfuqj8dd2w26hqw"
validator = "tnam1q985emxj29hpz3dlye0yfe5hm66pmwqalu0y06p4"
amount = "84180"
```

**Comment by Fraccaman** [comment]
okay so can use your tpknam address, but pls rename the file using as alias the github username of the forked repo (i.e [encapsulate-xyz](https://github.com/encapsulate-xyz/namada-mainnet-genesis/tree/submit-stage2))

**Comment by aditya-manit** [comment]
> okay so can use your tpknam address, but pls rename the file using as alias the github username of the forked repo (i.e [encapsulate-xyz](https://github.com/encapsulate-xyz/namada-mainnet-genesis/tree/submit-stage2))

ah sorry about that, I thought it was the username of the account who is raising the PR

Just made the changes, and have opened the PR for review as well, thanks

**Review by iskay — APPROVED** [review]

**Pull request merged**
