### PR TITLE
add supermanz-stark-bond.toml

### PR DESCRIPTION
**Pull request by SUPERMANZ-STARK**
## Discord handler
< insert here you discord handler (if you have one) >

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by iskay** [comment]
Can you please rename the file using only lowercase?

**Comment by SUPERMANZ-STARK** [comment]
> Can you please rename the file using only lowercase?

My apologies if I have done something incorrectly.  I 'think' I have done this requested edit (submitted a new file in lower case).  Could not immediately see an option for editing the name of the existing file -hence a new one.

**Comment by iskay** [comment]
ty but looks like you've only renamed the PR title, not the file itself

**Comment by SUPERMANZ-STARK** [comment]
OK.  I have just created an entirely new file/pull request (with the file in lower case), and submitted it.  Yoiu can disregard the original request.  Thanks for your patience :)

**Pull request closed without merging**
