### PR TITLE
nodersteam-bond.toml

### PR DESCRIPTION
**Pull request by nodersteam**
## Discord handler
noders

## Checklist before opening a pull request
- [x] My submissions follow the [instructions](https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA?view)
- [x] Im aware my submission will not be modifiable/delatable if merged

### CODE REVIEW

**Comment by Fraccaman** [comment]
pls change the filename alias to noderteam

**Comment by nodersteam** [comment]
> pls change the filename alias to noderteam

renamed

**Comment by Fraccaman** [comment]
sorry I meant you github alias i.e nodersteam (a `s` is missing)

**Comment by nodersteam** [comment]
> sorry I meant you github alias i.e nodersteam (a `s` is missing)

oh, sorry, I see worse at night)

Corrected

**Pull request merged**
